# Generated by Django 6.0.2 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_role_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, help_text='برای لندینگ مشاور/صاحب مشاوره — خالی=غیرفعال', max_length=120, verbose_name='اسلاگ'),
        ),
    ]
