# Generated by Django 6.0.2 on 2026-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_user_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolechangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'requested_role'), name='uniq_pending_rolechange_user_role'),
        ),
    ]
