# Generated by Django 6.0.2 on 2026-02-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=120)),
                ('en_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent category (tree structure).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uniq_category_slug'), models.UniqueConstraint(fields=('en_name',), name='uniq_category_en_name'), models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='category_parent_not_self')],
            },
        ),
    ]
