# Generated by Django 6.0.2 on 2026-02-15 09:46

import apps.common.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categoryimage_alter_category_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.category_image_upload_to),
        ),
    ]
