# Generated by Django 6.0.2 on 2026-02-16 16:56

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_categoryimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_name',
            field=models.CharField(max_length=120, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fa_name',
            field=models.CharField(max_length=120, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='intro_content',
            field=models.TextField(blank=True, verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر', verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='دسته والد (ساختار درختی)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=140, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
