# Generated by Django 6.0.2 on 2026-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_options_alter_category_allow_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('property', 'نوع ملک'), ('service', 'سرویس'), ('content_tag', 'تگ محتوایی')], db_index=True, default='property', max_length=24, verbose_name='نوع دسته\u200cبندی'),
        ),
    ]
