# Generated by Django 6.0.2 on 2026-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('property', 'نوع ملک'), ('project', 'پروژه'), ('service', 'سرویس'), ('content_tag', 'تگ محتوایی')], db_index=True, default='property', max_length=24, verbose_name='نوع دسته\u200cبندی'),
        ),
    ]
