# Generated by Django 6.0.5 on 2026-05-09 10:30

import apps.common.upload_utils
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0007_alter_category_category_type'),
        ('locations', '0011_add_employee_remove_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو')),
                ('seo_meta_description', models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا')),
                ('seo_h1', models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1')),
                ('seo_canonical', models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال')),
                ('seo_noindex', models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس')),
                ('allow_index', models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس')),
                ('seo_priority', models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو')),
                ('name', models.CharField(max_length=180, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('provider_type', models.CharField(choices=[('company', 'شرکت'), ('person', 'شخص')], db_index=True, default='company', max_length=12, verbose_name='نوع ارائه\u200cدهنده')),
                ('approval_status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='approved', max_length=12, verbose_name='وضعیت تأیید')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('intro_content', models.TextField(blank=True, verbose_name='متن معرفی')),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='محتوای اصلی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.common.upload_utils.service_provider_logo_upload_to, verbose_name='لوگو/تصویر پروفایل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('categories', models.ManyToManyField(limit_choices_to={'category_type': 'service'}, related_name='service_providers', to='categories.category', verbose_name='دسته\u200cهای سرویس')),
                ('cities', models.ManyToManyField(blank=True, related_name='service_providers', to='locations.city', verbose_name='شهرهای تحت پوشش')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مالک')),
            ],
            options={
                'verbose_name': 'ارائه\u200cدهنده سرویس',
                'verbose_name_plural': 'ارائه\u200cدهندگان سرویس',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.common.upload_utils.service_provider_image_upload_to, verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر شاخص')),
                ('is_landing_cover', models.BooleanField(default=False, verbose_name='کاور لندینگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.serviceprovider', verbose_name='ارائه\u200cدهنده')),
            ],
            options={
                'verbose_name': 'تصویر ارائه\u200cدهنده سرویس',
                'verbose_name_plural': 'تصاویر ارائه\u200cدهندگان سرویس',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
