# Generated by Django 6.0.2 on 2026-02-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_add_inquiry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('city', 'لندینگ شهر'), ('category', 'لندینگ دسته'), ('city_category', 'لندینگ شهر+دسته'), ('area_category', 'لندینگ محله+دسته'), ('contact', 'صفحه تماس با ما'), ('other', 'سایر')], db_index=True, max_length=20, verbose_name='نوع صفحه')),
                ('source_path', models.CharField(blank=True, help_text='مثال: tehran، apartment، tehran/apartment', max_length=255, verbose_name='مسیر صفحه')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('viewed', 'مشاهده شده'), ('contacted', 'تماس گرفته شده')], db_index=True, default='new', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'لید لندینگ',
                'verbose_name_plural': 'لیدهای لندینگ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('viewed', 'مشاهده شده'), ('contacted', 'تماس گرفته شده')], db_index=True, default='new', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'لید آگهی',
                'verbose_name_plural': 'لیدهای آگهی',
                'ordering': ('-created_at',),
            },
        ),
    ]
