# Generated by Django 6.0.2 on 2026-02-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_listinglead_first_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinglead',
            name='source_type',
            field=models.CharField(choices=[('city', 'لندینگ شهر'), ('category', 'لندینگ دسته'), ('area', 'لندینگ محله'), ('city_category', 'لندینگ شهر+دسته'), ('area_category', 'لندینگ محله+دسته'), ('contact', 'صفحه تماس با ما'), ('other', 'سایر')], db_index=True, max_length=20, verbose_name='نوع صفحه'),
        ),
    ]
