# Generated by Django 6.0.2 on 2026-02-15 09:46

import apps.common.upload_utils
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_alter_categoryimage_image'),
        ('locations', '0010_alter_areaimage_image_alter_cityimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('seo_meta_description', models.TextField(blank=True, help_text='Optional meta description override')),
                ('seo_h1', models.CharField(blank=True, help_text='Optional H1 override', max_length=255)),
                ('seo_canonical', models.URLField(blank=True, help_text='Optional canonical URL')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Force noindex for this page')),
                ('allow_index', models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules')),
                ('seo_priority', models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='خلاصه کوتاه برای کارت و meta')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.common.upload_utils.blog_cover_upload_to)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], db_index=True, default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='locations.area')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='locations.city')),
                ('listing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='categories.category', verbose_name='دسته\u200cبندی ملک')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ('-published_at', '-id'),
            },
        ),
    ]
