# Generated by Django 6.0.2 on 2026-02-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(help_text='Persian display name', max_length=120)),
                ('en_name', models.CharField(help_text='English name used for slug generation', max_length=120)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', max_length=140)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility in public pages')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordering priority')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uniq_province_slug'), models.UniqueConstraint(fields=('en_name',), name='uniq_province_en_name')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(help_text='Persian display name', max_length=120)),
                ('en_name', models.CharField(help_text='English name used for slug generation', max_length=120)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', max_length=140)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility in public pages')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordering priority')),
                ('province', models.ForeignKey(help_text='DB-only grouping; not used in URL', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.province')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(help_text='Persian display name', max_length=120)),
                ('en_name', models.CharField(help_text='English name used for slug generation', max_length=120)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', max_length=140)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility in public pages')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordering priority')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='locations.city')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('city', 'slug'), name='uniq_area_slug_in_city'), models.UniqueConstraint(fields=('city', 'en_name'), name='uniq_area_en_name_in_city')],
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('slug',), name='uniq_city_slug'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('en_name',), name='uniq_city_en_name'),
        ),
    ]
