# Generated by Django 6.0.2 on 2026-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='seo_canonical',
            field=models.CharField(blank=True, help_text='Canonical URL override (leave blank to auto-generate). مثال: /s/lahijan/', max_length=255),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_content_bottom',
            field=models.TextField(blank=True, help_text='Optional HTML/text content shown near bottom of page.'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_content_top',
            field=models.TextField(blank=True, help_text='Optional HTML/text content shown near top of page.'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Unique meta description (fallback will be generated if empty).'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='H1 for this page (fallback will be generated if empty).', max_length=255),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text="If true, set meta robots to 'noindex, follow'."),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Unique <title> for this page (fallback will be generated if empty).', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_canonical',
            field=models.CharField(blank=True, help_text='Canonical URL override (leave blank to auto-generate). مثال: /s/lahijan/', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_content_bottom',
            field=models.TextField(blank=True, help_text='Optional HTML/text content shown near bottom of page.'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_content_top',
            field=models.TextField(blank=True, help_text='Optional HTML/text content shown near top of page.'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Unique meta description (fallback will be generated if empty).'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='H1 for this page (fallback will be generated if empty).', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text="If true, set meta robots to 'noindex, follow'."),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Unique <title> for this page (fallback will be generated if empty).', max_length=255),
        ),
    ]
