# Generated by Django 6.0.2 on 2026-02-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_area_seo_canonical_area_seo_content_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='seo_canonical',
        ),
        migrations.RemoveField(
            model_name='area',
            name='seo_content_bottom',
        ),
        migrations.RemoveField(
            model_name='area',
            name='seo_content_top',
        ),
        migrations.RemoveField(
            model_name='area',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='area',
            name='seo_h1',
        ),
        migrations.RemoveField(
            model_name='area',
            name='seo_noindex',
        ),
        migrations.RemoveField(
            model_name='area',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_canonical',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_content_bottom',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_content_top',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_h1',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_noindex',
        ),
        migrations.RemoveField(
            model_name='city',
            name='seo_title',
        ),
    ]
