# Generated by Django 6.0.2 on 2026-02-08 20:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_area_seo_canonical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules'),
        ),
        migrations.AddField(
            model_name='area',
            name='intro_content',
            field=models.TextField(blank=True, help_text='Short intro shown at top of area landing page'),
        ),
        migrations.AddField(
            model_name='area',
            name='main_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Main area landing content'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='Optional canonical URL'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Optional H1 override', max_length=255),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='Optional meta description override'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Force noindex for this page'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)'),
        ),
        migrations.AddField(
            model_name='area',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules'),
        ),
        migrations.AddField(
            model_name='city',
            name='intro_content',
            field=models.TextField(blank=True, help_text='Short intro shown at top of city landing page'),
        ),
        migrations.AddField(
            model_name='city',
            name='main_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Main city landing content'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='Optional canonical URL'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Optional H1 override', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='Optional meta description override'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Force noindex for this page'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)'),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
    ]
