# Generated by Django 6.0.2 on 2026-02-14 14:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_cityimage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cityimage',
            new_name='locations_c_city_id_b12a11_idx',
            old_name='loc_cityimg_city_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='cityimage',
            new_name='locations_c_city_id_067123_idx',
            old_name='loc_cityimg_city_cover_idx',
        ),
        migrations.AlterField(
            model_name='area',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر — از دکمه تصویر در ویرایشگر استفاده کنید.'),
        ),
    ]
