# Generated by Django 6.0.2 on 2026-02-14 16:51

import apps.common.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_areaimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.area_image_upload_to),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.city_image_upload_to),
        ),
    ]
