# Generated by Django 6.0.2 on 2026-02-16 12:14

import apps.common.upload_utils
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_areaimage_image_alter_cityimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'محله', 'verbose_name_plural': 'محله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterField(
            model_name='area',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='area',
            name='en_name',
            field=models.CharField(help_text='نام انگلیسی برای ساخت اسلاگ', max_length=120, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='area',
            name='fa_name',
            field=models.CharField(help_text='نام نمایشی فارسی', max_length=120, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='area',
            name='intro_content',
            field=models.TextField(blank=True, help_text='متن کوتاه بالای صفحه محله', verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True, help_text='نمایش در صفحات عمومی', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='area',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر', verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(help_text='شناسه URL', max_length=140, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='area',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='اولویت نمایش', verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='areaimage',
            name='alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='areaimage',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.area', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='areaimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.area_image_upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='city',
            name='en_name',
            field=models.CharField(help_text='نام انگلیسی برای ساخت اسلاگ', max_length=120, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='fa_name',
            field=models.CharField(help_text='نام نمایشی فارسی', max_length=120, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='intro_content',
            field=models.TextField(blank=True, help_text='متن کوتاه بالای صفحه شهر', verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, help_text='نمایش در صفحات عمومی', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='city',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر', verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(help_text='گروه\u200cبندی در پایگاه داده', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(help_text='شناسه URL', max_length=140, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='اولویت نمایش', verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='alt',
            field=models.CharField(blank=True, help_text='برای سئو و دسترسی\u200cپذیری', max_length=180, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='caption',
            field=models.CharField(blank=True, help_text='لیبل نمایشی', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.city_image_upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='is_content_image',
            field=models.BooleanField(default=False, help_text='برای درج در محتوای ریچ\u200cتکست', verbose_name='تصویر محتوا'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='تصویر کارت شهر در لیست', verbose_name='تصویر شاخص کارت'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='is_landing_cover',
            field=models.BooleanField(default=False, help_text='تصویر بالای صفحه شهر', verbose_name='کاور لندینگ'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='province',
            name='en_name',
            field=models.CharField(help_text='نام انگلیسی برای ساخت اسلاگ', max_length=120, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='province',
            name='fa_name',
            field=models.CharField(help_text='نام نمایشی فارسی', max_length=120, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='province',
            name='is_active',
            field=models.BooleanField(default=True, help_text='نمایش در صفحات عمومی', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.SlugField(help_text='شناسه URL', max_length=140, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='province',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='اولویت نمایش', verbose_name='ترتیب'),
        ),
    ]
