# Generated by Django 6.0.2 on 2026-02-14 16:51

import apps.common.upload_utils
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0010_alter_areaimage_image_alter_cityimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('seo_meta_description', models.TextField(blank=True, help_text='Optional meta description override')),
                ('seo_h1', models.CharField(blank=True, help_text='Optional H1 override', max_length=255)),
                ('seo_canonical', models.URLField(blank=True, help_text='Optional canonical URL')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Force noindex for this page')),
                ('allow_index', models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules')),
                ('seo_priority', models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('intro_content', models.TextField(blank=True)),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.common.upload_utils.agency_logo_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('cities', models.ManyToManyField(blank=True, related_name='agencies', to='locations.city')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_agency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشاوره املاک',
                'verbose_name_plural': 'مشاوره\u200cهای املاک',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.common.upload_utils.agency_image_upload_to)),
                ('alt', models.CharField(blank=True, max_length=180)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('is_landing_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'تصویر مشاوره',
                'verbose_name_plural': 'تصاویر مشاوره',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
