# Generated by Django 6.0.2 on 2026-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
