# Generated by Django 6.0.2 on 2026-02-16 12:14

import apps.common.upload_utils
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agencyjoinrequest'),
        ('locations', '0011_add_employee_remove_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='locations.city', verbose_name='شهرها'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='intro_content',
            field=models.TextField(blank=True, verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.upload_utils.agency_logo_upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=180, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agencies.agency', verbose_name='مشاوره املاک'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.agency_image_upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='is_landing_cover',
            field=models.BooleanField(default=False, verbose_name='کاور لندینگ'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.CreateModel(
            name='EmployeeRemoveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_requests', to='agencies.agency', verbose_name='مشاوره املاک')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_remove_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_requests', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'درخواست حذف کارمند',
                'verbose_name_plural': 'درخواست\u200cهای حذف کارمند',
                'ordering': ('-created_at',),
            },
        ),
    ]
