# Generated by Django 6.0.2 on 2026-02-27 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_add_employee_remove_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agencyjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'agency'), name='uniq_pending_join_user_agency'),
        ),
        migrations.AddConstraint(
            model_name='employeeremoverequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'agency'), name='uniq_pending_remove_user_agency'),
        ),
    ]
