# Generated by Django 6.0.2 on 2026-02-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_agencyjoinrequest_uniq_pending_join_user_agency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyEmployeeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('canceled', 'لغو شده')], db_index=True, default='pending', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_invites', to='agencies.agency', verbose_name='املاک')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_invites_sent', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_invites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دعوت\u200cشده')),
            ],
            options={
                'verbose_name': 'دعوت همکاری در املاک',
                'verbose_name_plural': 'دعوت\u200cهای همکاری در املاک',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('invited_user', 'agency'), name='uniq_pending_invite_user_agency')],
            },
        ),
    ]
