# Generated by Django 6.0.2 on 2026-02-09 11:47

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_allow_index_category_intro_content_and_more'),
        ('locations', '0004_area_allow_index_area_intro_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('seo_meta_description', models.TextField(blank=True, help_text='Optional meta description override')),
                ('seo_h1', models.CharField(blank=True, help_text='Optional H1 override', max_length=255)),
                ('seo_canonical', models.URLField(blank=True, help_text='Optional canonical URL')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Force noindex for this page')),
                ('allow_index', models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules')),
                ('seo_priority', models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('deal', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], db_index=True, default='buy', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, help_text='Short summary for meta description / cards')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Main listing description')),
                ('price', models.BigIntegerField(blank=True, help_text='Main price (buy or rent)', null=True)),
                ('price_unit', models.CharField(blank=True, help_text='e.g. تومان / دلار / متر', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.city')),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['status', 'deal'], name='listings_li_status_764d85_idx'), models.Index(fields=['city', 'area', 'category'], name='listings_li_city_id_043958_idx'), models.Index(fields=['published_at'], name='listings_li_publish_32106c_idx'), models.Index(fields=['slug'], name='listings_li_slug_a2fd83_idx')],
            },
        ),
    ]
