# Generated by Django 6.0.2 on 2026-02-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('alt', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['listing', 'sort_order'], name='listings_li_listing_7515ff_idx'), models.Index(fields=['listing', 'is_cover'], name='listings_li_listing_7c3dcd_idx')],
            },
        ),
    ]
