# Generated by Django 6.0.2 on 2026-02-16 16:56

import apps.common.upload_utils
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_add_employee_remove_request'),
        ('categories', '0005_alter_category_options_alter_category_allow_index_and_more'),
        ('listings', '0008_add_rejected_status'),
        ('locations', '0011_add_employee_remove_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-published_at', '-id'), 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'تصویر آگهی', 'verbose_name_plural': 'تصاویر آگهی'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='agencies.agency', verbose_name='مشاوره املاک'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.area', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='محتوای اصلی آگهی', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_unit',
            field=models.CharField(blank=True, help_text='مثال: تومان، دلار، تومان/روز', max_length=32, verbose_name='واحد قیمت'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='short_description',
            field=models.TextField(blank=True, help_text='خلاصه برای meta و کارت آگهی', verbose_name='خلاصه کوتاه'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.listing_image_upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='آگهی'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
