# Generated by Django 6.0.2 on 2026-02-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_options_alter_listingimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='انتخاب روی نقشه هنگام ثبت آگهی', max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='انتخاب روی نقشه هنگام ثبت آگهی', max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
