# Generated by Django 6.0.2 on 2026-02-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_add_listing_lat_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.listing', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'استعلام آگهی',
                'verbose_name_plural': 'استعلام\u200cهای آگهی',
                'ordering': ('-created_at',),
            },
        ),
    ]
