# Generated by Django 6.0.2 on 2026-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_add_listing_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinginquiry',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('viewed', 'مشاهده شده'), ('contacted', 'تماس گرفته شده')], db_index=True, default='new', max_length=12, verbose_name='وضعیت'),
        ),
    ]
