# Generated by Django 6.0.2 on 2026-02-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_add_inquiry_status"),
        ("lead", "0002_migrate_listing_inquiry"),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingInquiry',
        ),
    ]
