# Generated by Django 6.0.2 on 2026-02-08 22:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_allow_index_category_intro_content_and_more'),
        ('locations', '0004_area_allow_index_area_intro_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAreaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('seo_meta_description', models.TextField(blank=True, help_text='Optional meta description override')),
                ('seo_h1', models.CharField(blank=True, help_text='Optional H1 override', max_length=255)),
                ('seo_canonical', models.URLField(blank=True, help_text='Optional canonical URL')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Force noindex for this page')),
                ('allow_index', models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules')),
                ('seo_priority', models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)')),
                ('intro_content', models.TextField(blank=True, help_text='Intro content shown above listings')),
                ('main_content', ckeditor.fields.RichTextField(blank=True, help_text='Main SEO content for area+category landing')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this override will be ignored')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_area_categories', to='locations.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_area_categories', to='categories.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_area_categories', to='locations.city')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('area', 'category'), name='uniq_area_category_landing')],
            },
        ),
        migrations.CreateModel(
            name='CityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('seo_meta_description', models.TextField(blank=True, help_text='Optional meta description override')),
                ('seo_h1', models.CharField(blank=True, help_text='Optional H1 override', max_length=255)),
                ('seo_canonical', models.URLField(blank=True, help_text='Optional canonical URL')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Force noindex for this page')),
                ('allow_index', models.BooleanField(default=True, help_text='If false, page will be noindex regardless of other rules')),
                ('seo_priority', models.PositiveSmallIntegerField(default=5, help_text='SEO priority for sitemap / crawl budget (1-10)')),
                ('intro_content', models.TextField(blank=True, help_text='Intro content shown above listings')),
                ('main_content', ckeditor.fields.RichTextField(blank=True, help_text='Main SEO content for city+category landing')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this override will be ignored')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_city_categories', to='categories.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_city_categories', to='locations.city')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('city', 'category'), name='uniq_city_category_landing')],
            },
        ),
    ]
