# Generated by Django 6.0.2 on 2026-02-16 16:56

import apps.common.upload_utils
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_options_alter_category_allow_index_and_more'),
        ('locations', '0011_add_employee_remove_request'),
        ('seo', '0002_citycategoryimage_cityareacategoryimage_alter_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityareacategory',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'لندینگ محله+دسته', 'verbose_name_plural': 'لندینگ\u200cهای محله+دسته'},
        ),
        migrations.AlterModelOptions(
            name='citycategory',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'لندینگ شهر+دسته', 'verbose_name_plural': 'لندینگ\u200cهای شهر+دسته'},
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_area_categories', to='locations.area', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_area_categories', to='categories.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_area_categories', to='locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='intro_content',
            field=models.TextField(blank=True, help_text='متن بالای لیست آگهی\u200cها', verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، این تنظیمات اعمال نمی\u200cشود', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر', verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='cityareacategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='cityareacategoryimage',
            name='alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='cityareacategoryimage',
            name='city_area_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seo.cityareacategory', verbose_name='لندینگ محله+دسته'),
        ),
        migrations.AlterField(
            model_name='cityareacategoryimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.area_category_image_upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='allow_index',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، صفحه ایندکس نمی\u200cشود', verbose_name='مجوز ایندکس'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_city_categories', to='categories.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_city_categories', to='locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='intro_content',
            field=models.TextField(blank=True, help_text='متن بالای لیست آگهی\u200cها', verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال، این تنظیمات اعمال نمی\u200cشود', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='محتوا با امکان درج و آپلود تصویر', verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='URL کانونیکال', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='عنوان H1 جایگزین', max_length=255, verbose_name='عنوان H1'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='توضیحات جایگزین meta description', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='عدم ایندکس شدن صفحه', verbose_name='بدون ایندکس'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='اولویت برای sitemap (۱ تا ۱۰)', verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوان جایگزین برای سئو', max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='citycategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='citycategoryimage',
            name='alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='citycategoryimage',
            name='city_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seo.citycategory', verbose_name='لندینگ شهر+دسته'),
        ),
        migrations.AlterField(
            model_name='citycategoryimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_utils.city_category_image_upload_to, verbose_name='تصویر'),
        ),
    ]
