"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path

# BASE_DIR points to: .../vidahome/config
BASE_DIR = Path(__file__).resolve().parent.parent

# PROJECT_DIR points to: .../vidahome (root next to manage.py)
PROJECT_DIR = BASE_DIR.parent


SECRET_KEY = 'django-insecure-sc&5zea_zsxyfgxqw_2e3@y5u7fpgl$)u+&)x(8h@3@+6l5l5q'
DEBUG = True
ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',

    "apps.common",
    "apps.locations",
    "apps.categories",
    "apps.attributes",
    "apps.listings",
    "apps.blog",
    "apps.seo",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # root-based templates (next to manage.py)
        'DIRS': [PROJECT_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.common.context_processors.header_cities',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # DB next to manage.py (root)
        'NAME': PROJECT_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Iran-ready defaults (optional to keep en-us/UTC if you prefer)
LANGUAGE_CODE = 'fa'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True


# Static & media (root-based)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]
STATIC_ROOT = PROJECT_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = PROJECT_DIR / "media"
# مسیر واحد آپلود: CKEditor و تصاویر محتوا در uploads/ ذخیره می‌شوند
CKEDITOR_UPLOAD_PATH = "uploads/"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
