"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# BASE_DIR points to: .../vidahome/config
BASE_DIR = Path(__file__).resolve().parent.parent

# PROJECT_DIR points to: .../vidahome (root next to manage.py)
PROJECT_DIR = BASE_DIR.parent

# override=True تا مقدار .env همیشه اعمال شود (حتی اگر قبلاً در محیط ست شده باشد)
load_dotenv(PROJECT_DIR / ".env", override=True)


SECRET_KEY = 'django-insecure-sc&5zea_zsxyfgxqw_2e3@y5u7fpgl$)u+&)x(8h@3@+6l5l5q'
DEBUG = True
ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'ckeditor',
    'ckeditor_uploader',

    "apps.common",
    "apps.locations",
    "apps.categories",
    "apps.seo",
    "apps.agencies",
    "apps.accounts",
    "apps.panel",
    "apps.attributes",
    "apps.listings",
    "apps.blog",
    "apps.lead",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'apps.common.middleware.AdminLocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.common.middleware.AdminAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # root-based templates (next to manage.py)
        'DIRS': [PROJECT_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.common.context_processors.header_cities',
                'apps.panel.context_processors.panel_neshan_api_key',
                'apps.panel.context_processors.panel_pending_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # DB next to manage.py (root)
        'NAME': PROJECT_DIR / 'db.sqlite3',
    }
}

# Cache برای django-ratelimit و سایر موارد
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "OPTIONS": {"MAX_ENTRIES": 10000},
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Iran-ready defaults (optional to keep en-us/UTC if you prefer)
LANGUAGE_CODE = 'fa'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True


# Static & media (root-based)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]
STATIC_ROOT = PROJECT_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = PROJECT_DIR / "media"
# همه تصاویر با Pillow به WebP تبدیل می‌شوند
STORAGES = {
    "default": {
        "BACKEND": "apps.common.storage.WebPImageStorage",
        "OPTIONS": {
            "location": PROJECT_DIR / "media",
            "base_url": "/media/",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
# مسیر واحد آپلود: CKEditor و تصاویر محتوا در uploads/ ذخیره می‌شوند
CKEDITOR_UPLOAD_PATH = "uploads/"
# نام یکتای خودکار برای تصاویر ریچ‌تکست — وابسته به نام فایل ورودی نیست
CKEDITOR_FILENAME_GENERATOR = "apps.common.upload_utils.unique_filename"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

# ریدایرکت بعد از ورود در views انجام می‌شود (superuser→admin، بقیه→panel)
LOGIN_REDIRECT_URL = "/panel/"
LOGIN_URL = "/accounts/login/"

# نقشه نشان
NESHAN_API_KEY = os.environ.get("NESHAN_API_KEY", "")
# کلید سرویس برای Reverse Geocoding (تبدیل مختصات به شهر/محله)؛ در صورت نبود از NESHAN_API_KEY استفاده می‌شود
NESHAN_SERVICE_API_KEY = os.environ.get("NESHAN_SERVICE_API_KEY", "") or os.environ.get("NESHAN_API_KEY", "")

# KaveNegar SMS — مستندات: https://kavenegar.com/rest.html
KAVENEGAR_API_KEY = (os.environ.get("KAVENEGAR_API_KEY", "") or "").strip()
KAVENEGAR_SENDER = (os.environ.get("KAVENEGAR_SENDER", "9982002624") or "9982002624").strip()
KAVENEGAR_OTP_TEMPLATE = os.environ.get("KAVENEGAR_OTP_TEMPLATE", "login")
