# Generated by Django 6.0.2 on 2026-02-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_alter_categoryimage_image'),
        ('listings', '0003_listing_agency_listing_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام فارسی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('value_type', models.CharField(choices=[('integer', 'عددی'), ('boolean', 'بله/خیر'), ('choice', 'انتخابی'), ('string', 'متن آزاد')], max_length=16, verbose_name='نوع مقدار')),
                ('unit', models.CharField(blank=True, help_text='مثال: اتاق، متر، سال', max_length=32, verbose_name='واحد')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(blank=True, help_text='ویژگی فقط برای این دسته\u200cها نمایش داده می\u200cشود', related_name='attributes', to='categories.category', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120, verbose_name='مقدار')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='attributes.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'گزینه ویژگی',
                'verbose_name_plural': 'گزینه\u200cهای ویژگی',
                'ordering': ('sort_order', 'id'),
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ListingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='مقدار بله/خیر')),
                ('value_str', models.CharField(blank=True, max_length=500, verbose_name='مقدار متن')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_values', to='attributes.attribute', verbose_name='ویژگی')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='listings.listing', verbose_name='آگهی')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_values', to='attributes.attributeoption', verbose_name='مقدار انتخابی')),
            ],
            options={
                'verbose_name': 'ویژگی آگهی',
                'verbose_name_plural': 'ویژگی\u200cهای آگهی',
                'ordering': ('attribute__sort_order', 'attribute_id'),
                'unique_together': {('listing', 'attribute')},
            },
        ),
    ]
