# Generated by Django 6.0.2 on 2026-02-15 12:50

from django.db import migrations, models


def copy_value_option_to_value_str(apps, schema_editor):
    ListingAttribute = apps.get_model("attributes", "ListingAttribute")
    for la in ListingAttribute.objects.filter(value_option_id__isnull=False).select_related("value_option"):
        la.value_str = la.value_option.value
        la.save(update_fields=["value_str"])


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_value_option_to_value_str, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='listingattribute',
            name='value_option',
        ),
        migrations.AlterField(
            model_name='listingattribute',
            name='value_str',
            field=models.CharField(blank=True, help_text='برای عددی از value_int، برای بله/خیر از value_bool استفاده شود', max_length=500, verbose_name='مقدار متن / انتخابی'),
        ),
        migrations.DeleteModel(
            name='AttributeOption',
        ),
    ]
