# Generated by Django 6.0.2 on 2026-02-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_remove_attribute_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingattribute',
            name='value_str',
            field=models.CharField(blank=True, help_text='برای عددی از value_int، برای بله/خیر از value_bool استفاده شود', max_length=500, verbose_name='مقدار متن'),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120, verbose_name='مقدار')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='attributes.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'گزینه ویژگی',
                'verbose_name_plural': 'گزینه\u200cهای ویژگی',
                'ordering': ('sort_order', 'id'),
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='listingattribute',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_values', to='attributes.attributeoption', verbose_name='مقدار انتخابی'),
        ),
    ]
