# Generated by Django 6.0.2 on 2026-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_add_attribute_option_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_filterable',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این ویژگی در سایدبار فیلتر صفحه آگهی\u200cها نمایش داده می\u200cشود', verbose_name='نمایش در فیلترها'),
        ),
    ]
