# Generated by Django 6.0.2 on 2026-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_add_is_filterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='icon',
            field=models.CharField(blank=True, help_text='کلاس آیکون Finder مثل fi-bed, fi-bath, fi-car برای نمایش در صفحه جزئیات آگهی', max_length=64, verbose_name='آیکون'),
        ),
    ]
