# Generated by Django 6.0.2
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_add_attribute_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='icon',
        ),
    ]
