# Generated by Django 6.0.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_remove_attribute_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='icon',
            field=models.FileField(
                blank=True,
                help_text='فقط PNG یا SVG، حداکثر ۶۴ کیلوبایت، ابعاد حداکثر ۱۲۸×۱۲۸',
                null=True,
                upload_to='attribute_icons/',
                verbose_name='آیکون',
            ),
        ),
    ]
