# Generated by Django 6.0.2 on 2026-02-27 01:04

import apps.attributes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_add_attribute_icon_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='icon',
            field=models.FileField(blank=True, help_text='فقط PNG یا SVG، حداکثر ۶۴ کیلوبایت، ابعاد حداکثر ۱۲۸×۱۲۸', null=True, upload_to='attribute_icons/', validators=[apps.attributes.validators.validate_attribute_icon], verbose_name='آیکون'),
        ),
    ]
